// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dptmmfreazjdxtahfjgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdG1tZnJlYXpqZHh0YWhmamdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTU4MTEsImV4cCI6MjA2OTU3MTgxMX0.cr1f6G_0IFXncN8kt4rcxwfZ8zw5AeoeBBOUP_9x4qk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});